### Introducción

El objeto principal del presente capítulo consiste en revisar los antecedentes sísmicos del sitio del proyecto e identificar la información crítica necesaria para poder efectuar un análisis de la estabilidad sísmica de las presas de relaves B1 y B2 del sitio de Jacobina, de acuerdo al estado actual de la práctica internacional. Los análisis de estabilidad sísmca son una parte fundamental de los estudios de seguridad de la presa (DSI) que está llevando a cabo el equipo de diseño de SRK.

### Antecedentes

Entre los antecedentes relevantes, se ha identificado un estudio sismológico detallado de la región de Jacobina (REF), desarrollado durante 2021 por el profesor Carlos Uchoa a raíz de la ocurrencia de eventos sísmicos moderados en el mes de diciembre de 2020. Los estudios de paleo-sismicidad mostraron evidencias de sismos muy importantes que ocurrieron en diferentes edades de la corteza. Mediante la correlación de mapas de alineamientos magnéticos con eventos sísmicos más recientes (con magnitudes menores a 3-4), el estudio de referencia pudo constatar indicios de la posible reactivación de un sistema de fallas donde se encuentra la Serra de Jacobina. El estudio de referencia presentó estimaciones de los tiempos de recurrencia de eventos moderados de magnitud mayor a M=5.0 con períodos de retorno de 10,000 años. Sin embargo, debido a que las estimaciones se basaron en la geofísica de los bloques geo-tectónicos, y no incluyeron sismicidad histórica, el reporte no presenta estimaciones de los parámetros de recurrencia de Gutemberg-Richter, que se requieren en un modelo de peligrosidad sísmica para estimar las intensidades sísmicas del sitio del proyecto.

La empresa SENAI/CIMATEC preparó un reporte de monitoreo sismográfico que tuvo como objetivo el análisis de vibraciones en diferentes secciones de la presa de relaves. El reporte consideró como fuentes de vibración las originadas por voladuras de desmonte en áreas cercana, y originadas por la operación misma de la presa de relaves. El reporte no consideró otras fuentes de movimientos sísmicos del terreno.

El antecedente más importante relacionado con el análisis de estabilidad sísmica de la presa es el reporte JMC02-390-C-RL-009 (Proyecto Ejecutivo 5ta etapa de Recrecimiento) del mes de Marzo de 2020. Este reporte, presentó una síntesis de estudios efectuados para la ingeniería de detalle de la 5ta etapa de recrecimiento de la presa de relaves B2 y proporciona en la sección 4.3 algunos lineamientos sobre las intensidades sísmicas de diseño. El reporte de referencia consideró intensidades sísmicas de diseño a partir los mapas regionales de aceleraciones de la norma brasileira NBR 15421, que reporta aceleraciones en roca de 0.025 g (0.24 m/s2) con una probabilidad del 10% de ser excedidas en 50 años, equivalentes a un período de retorno de 1:475 años. El informe presenta valores de aceleración horizontal para otras condiciones geotécnias además de suelo firme, y estima los valores de diseño mediante la metodología de una norma sísmica de edificios y estructuras. Por otra parte, el informe cita valores de otras normas de referencia para presas de tierra de 0.05 g y 0.03 g para direcciones horizontales y verticales.

### Sismos de diseño

El estado actual de la práctica del diseño sísmico de presas y depósitos de relaves se basa en las fiosofías de diseño sísmico basado en el desempeño y define a los sismos de diseño a partir de una probabilidad anual de excedencia dependiente del grado de consecuencias de una falla de la instalación y de la etapa de la vida útil en la que se considera a dicha instalación (construcción, operación, cierre y post-cierre)

Las filosofías basadas en desmpeño básicamente consideran dos niveles de servicio: un sismo operativo de diseño para las etapas de cuidado activo, y un sismo máximo de diseño para las etapas de cuidado pasivo.

Las definición de dos niveles de servicio para una instalación, asume como premisa que los daños (deformaciones residuales) luego de un evento sísmico que ocurra durante las etapas de cuidado activo, permitirán al operador de la mina implementar medidas de reparación y rehabilitación (mitigación) para evitar una falla catastrófica de la instalación (por ejemplo la pérdida no controlada del contenido de un depósito de relaves), que normalmente no serían posibles durante las etapas de post-cierre.

<!-- La definición de intensidades sísmicas de diseño (niveles de servicio) diferentes entre las etapas de operación y cierre, tiene implícito que la ocurrencia de un evento sísmico extremo durante las etapas de operacion, en donde ocurren intensidades sísmicas mayores a las de diseño de la instalación, producirá daños que podrán sacar de servicio a la operación por un tiempo breve, pero no producirán el colapso de la misma. Del mismo modo, durante las etapas de post-cierre (cuidado pasivo) no serán posibles medidas de mitigacion y las instalaciones criticas con alto grado de consecuencias para la vida y el medio ambiente, deberán ser diseñadas con los sismos máximos de diseño o bien el sismo máximo creíble que pueda esperarse en esa región (bajas probabilidades de excedencia) -->

Como referencia, las tablas que siguen muestran valores de probabilidades anuales de excedencia (períodos de retorno) para diferentes etapas del proyecto y diferentes grados de consecuencia, de acuerdo a la recomendación DEL Canadian Dam Association (CDA) @CDA2014 y del Global Industry Standard on Tailing Management (GISTM) @GISTM2020

```{r include=TRUE}
#| layout-ncol: 2
#| column: body-outset-right
#| tbl-cap: "AEP y Grado de Consecuencias"
#| tbl-subcap: 
#|   - "Canadian Dam Association (CDA)"
#|   - "Global Industry Standard on Tailing Management (GISTM)"
TBL_AEP_CDA
TBL_AEP_GISTM
```

A partir de un estudio de peligrosidad sísmica del sitio, es posible conocer las curvas de probabilidad de excedencia de aceleraciones en suelo duro, que permiten obtener los sismos de diseño de acuerdo basados en riesgo para cada etapa de la instalación

### Conclusiones 

Como parte de la revisión de antecentes requeridos para las etapas de inspección de seguridad de la presa (DSI), se identificaron algunos reportes relevantes. El estudio sismológico presenta una descripción detallada del marco tectónico regional y una estimación de la actividad neotectónica de eventos de los últimos 10,000 años, basado en análisis geofísicos y no reportó parámetros de productividad basados en la sismicidad histórica. El reporte de DAM (JMC02-390-C-RL-009) presentó una estimación de las aceleraciones horizontales del proyecto basado en la norma para edificios y estructuras NBR 15421, cuyos mapas de peligrosidad sísmica sólo reportan intensidades sísmicas con probabilidades de excedencia de 1:475 años.

Los antecedentes disponibles a la fecha de redacción del presente capítulo, no informan las intensidades sísmicas (aceleraciones horizontales) de diseño que se requieren para el análisis de la estabilidad sísmica en construcción, operación o cierre de las presas de relaves B1 y B2. De acuerdo a la normativa brasileira ABNT NBR 13028 y las recomendaciones del CDA @CDA2014, se requieren sismos de diseño para diferentes probabilidades anuales de excedencia (períodos de retorno) que se obtienen a partir de un análisis de peligrosidad sísmica del sitio. A la fecha de redacción del presente informe, no se identificaron estudios de peligrosidad sísmica preparados específicamente para el sitio del proyecto

### Recomendaciones 

-   Se recomienda la elaboración de un estudio probabilístico de peligrosidad sísmica (PSHA) del sitio de Jacobina que proporcione curvas de probabilidad de excedencia de aceleraciones horizontales en suelo duro. Los alcances mínimos de dicho estudio deberían contemplar la preparación de espectros de amenaza uniforme de respuesta sísmica para intensidades en roca o suelo firme, considerando tanto valores medios como así tambien ramas de los fractiles 50%, 16%-84%, 10%-90% y 5%-95%.

-   Para la la definición de las probabilidades anuales de excedencia (períodos de retorno) de los sismos de diseño del sitio del proyecto de jacobina se recomiendan los lineamientos de la norma brasileira ABNT 13028 basdadas en las recomendaciones del Canadian Dam Association (CDA) @CDA2014  o las recomendaciones del Global Industry Standard on Tailing Management (GISTM) @GISTM2020

-   Para la definición de los sismos de diseño para las presas B1 y B2, se recomienda efectuar un estudio de respuesta dinámica de sitio que estime la amplificación por efectos de sitio del suelo de fundación de las presas B1 y B2, a partir de los estudios geotécnicos disponibles El estudio de peligrosidad sísmica deberá reportar los espectros de diseño sísmico de amenaza uniforme para diferentes condiciones geotécnicas de acuerd a ASCE 7-22 @ASCE722

### Descargo de responsabilidad {.unnumbered}

*Las opiniones expresadas en este Informe en línea se han basado en la información suministrada a* {{< var SRK >}}*. SRK ha actuado con el debido cuidado al revisar la información entregada. Si bien SRK ha comparado los datos clave suministrados con los valores esperados, la exactitud de los resultados y conclusiones de la revisión dependen enteramente de la exactitud e integridad de los datos suministrados. SRK no acepta responsabilidad por errores u omisiones en la información suministrada y no acepta ninguna responsabilidad consecuente que surja de decisiones o acciones comerciales que resulten de ellos. Las opiniones presentadas en este informe se aplican a las condiciones y características del sitio tal como existían al momento de las investigaciones de SRK, y aquellas razonablemente previsibles. Estas opiniones no se aplican necesariamente a las condiciones y características que puedan surgir después de la fecha de este Informe, sobre las cuales SRK no tenía conocimiento previo ni tuvo la oportunidad de evaluar.*

### Referencias {.unnumbered}

::: {#refs}
:::
