::: {.panel-tabset}

# SP


## Revisión de antecedentes sísmicos


El objeto principal del presente capítulo consiste en revisar los antecedentes sísmicos del sitio del proyecto e identificar la información crítica necesaria para poder efectuar un análisis de la estabilidad sísmica de las presas de relaves B1 y B2 del sitio de Jacobina, de acuerdo al estado actual de la práctica internacional. Los análisis de estabilidad sísmca son una parte fundamental de los estudios de seguridad de la presa (DSI) que está llevando a cabo el equipo de diseño de SRK.

Entre los antecedentes relevantes, se ha identificado un estudio sismológico detallado de la región de Jacobina (REF), desarrollado durante 2021, motivado por la ocurrencia de eventos sísmicos moderados en el mes de diciembre de 2020.  El análisis de la sismicidad y la tectónica de la región es un paso clave para poder comprender los mecanismos de generación del movimiento sísmico y poder definir la productividad de diferentes zonas mediante modelos de zonificación sísmica específicos, definidos a unos 500 km a la redonda del sitio de estudio.
El estudio sismológico presentó algunas estimaciones de los tiempos de recurrencia de eventos moderados de magnitud mayor a M=5.0 con períodos de retorno de 10,000 años. Sin embargo, debido a que las estimaciones se basaron en la geofísica de los bloques geo-tectónicos, y no incluyeron sismicidad histórica, el reporte no presenta estimaciones de los parámetros de recurrencia de Gutemberg-Richter, que se requieren para la definicion de un modelo de zonificación sísmica adecuado para la estimación del peligro sísmico de la región. Los estudios de paleo-sismicidad mostraron evidencias de sismos muy importantes que ocurrieron en diferentes edades de la corteza. No existen registros de sismicidad históirica. Mediante la correlación de mapas de alineamientos magnéticos con eventos sísmicos más recientes (con magnitudes menores a 3-4),  el estudio de referencia pudo constatar indicios de la posible reactivación de un sistema de fallas donde se encuentra la Serra de Jacobina. 

La empresa SENAI/CIMATEC preparó un reporte de monitoreo sismográfico que tuvo como objetivo el análisis de vibraciones en diferentes secciones de la presa de relaves. El reporte consideró como fuentes de vibración las originadas por voladuras de desmonte en áreas cercana, y originadas por la operación misma de la presa de relaves.


El antecedente más relevante relacionado con el análisis de estabilidad sísmica de la presa es el reporte JMC02-390-C-RL-009 (Proyecto Ejecutivo 5ta etapa de Recrecimiento) del mes de Marzo de 2020. Este reporte, presentó una síntesis de estudios efectuados para la ingeniería de detalle de la 5ta etapa de recrecimiento de la presa de relaves B2 y proporciona en la sección 4.3 algunos lineamientos sobre las intensidades sísmicas de diseño. El reporte de referencia consideró intensidades sísmicas de diseño a partir los mapas regionales de aceleraciones de la norma brasileira NBR 15421, que reporta aceleraciones en roca de 0.025 g (0.24 m/s2) con una probabilidad del 10% de ser excedidas en 50 años, equivalentes a un período de retorno de 1:475 años. El informe presenta valores de aceleración horizontal para otras condiciones geotécnias además de suelo firme, y estima los valores de diseño mediante la metodología de una norma sísmica de edificios y estructuras. Por otra parte, el informe cita valores de otras normas de referencia para presas de tierra de 0.05 g y 0.03 g para direcciones horizontales y verticales.

El estado actual de la práctica del diseño sísmico de presas e instalaciones críticas en general, requiere la definición de intensidades sísmicas de diseño con probabilidades de excedencia de intensidades asociadas al grado de consecuencias de una falla de la instalación. Las instalaciones cuya eventual falla no afecte vidas humanas o tengan un impacto muy bajo sobre el medio ambiente, se consideran de bajo riesgo y emplean intensidades sísmicas similares a las empleadas por los reglamentos para esructuras civiles. Las instalaciones que por otra parte pueden causar un daño mayor al ambiente o la perdida considerable de vidas humanas, suelen diseñarse con intensidades sísmicas más altas, asociadas a probabilidades de excedencia mucho más bajas (períodos de retorno más largos)


Por otra parte, el estado actual de la práctica establece intensidades sísmicas de diseño para cierre (passive-care) mucho mayores a las requeridas para las etapas de construcción y operación (active-care) a partir de la premisa en que la ocurrencia de un evento sísmico de determinada intensidad que ocurra durante las etapas de cuidado activo, permiten al operador implementar medidas de reparación y rehabilitación (mitigación) que normalmente no serían posibles durante la etapa de post-cierre. Como referencia, las tablas que siguen muestran  valores de probabilidades anuales de excedencia (períodos de retorno) recomendadas por la norma austrlaliana ANCOLD, la norma canadiense CDA y el estándard internacional GISTM, con períodos de retorno que van en general desde los 500 hasta los 10,000 años.

Las intensidades sísmicas para diferentes probabilidades anuales de excedencia (períodos de retorno) sólo pueden obtenerse a partir de un análisis de peligrosidad sísmica del sitio. Los mapas de peligrosidad sísmica de la región de Jacobina de la norma brasilera NBR , sólo reportan intensidades sísmicas de 1:475 años.


## Conclusiones y recomendaciones

- Los estudios de referencia disponibles a la fecha no proporcionan intensidades sísmicas para el sitio del proyecto consistentes con el estado actual de la práctica actual del diseño sísmico de presas de relaves para construcción, operación o cierre.

- Las intensidades sísmicas para diferentes probabilidades anuales de excedencia (períodos de retorno) sólo pueden obtenerse a partir de un análisis de peligrosidad sísmica del sitio.. A la fecha de redacción del presente informe, no se identificaron estudios de peligrosidad sísmica preparados específicamente para el sitio del proyecto

- Se recomienda la elaboración de un estudio probabilístico de peligrosidad sísmica (PSHA) del sitio de Jacobina.  Los alcances mínimos de dicho estudio deberían contemplar la preparación de espectros de amenaza uniforme de respuesta sísmica para intensidades en roca o suelo firme, para períodos de retorno consistentes con los estándares internacionales considerando tanto valores medios como así tambien ramas de los fractiles 50%, 16%-84%, 10%-90% y 5%-95%. 

- Se recomienda efectuar un estudio de respuesta dinámica de sitio y calibrar la posible amplificación por efectos de sitio del suelo de fundación de las presas B1 y B2, a partir de los estudios geotécnicos disponibles El estudio de peligrosidad sísmica deberá reportar los espectros de diseño sísmico de amenaza uniforme para diferentes condiciones geotécnicas de acuerd a ASCE 7-22

- Se recomienda que los modeladores del peligro sísmico incluyan como revisores del modelo PSHA, a los especialistas que conformaron el estudio de sismología (entre otros) para validar la consistencia de los modelos de zonificación y productividad sísmica empleados, con la tectónica y la sismicidad de la región de Jacobina


## Referencias

::: {#refs}
:::

## Descargo de responsabilidad

# EN

## Introduction

{{< var SRK >}} has been engaged by {{< var CLIENT >}}, to conduct the 2022 dam safety inspection (DSI) of both Jacobina’s tailings storage facilities (TSFs) (i.e.: B1 and B2). Jacobina mine is located in Jacobina Township, in the state of Bahia, in the countryside approximately 17 km from the Jacobina city center and 330 kilometres northeast of the city of Salvador, Bahia, Brazil. This work was achieved under purchase order PO#22000725 OL.

## Disclaimer

*The opinions expressed in this online Report have been based on the information supplied to* {{< var SRK >}}*. SRK has exercised all due care in reviewing the supplied information. Whilst SRK has compared key supplied data with expected values, the accuracy of the results and conclusions from the review are entirely reliant on the accuracy and completeness of the supplied data. SRK does not accept responsibility for any errors or omissions in the supplied information and does not accept any consequential liability arising from commercial decisions or actions resulting from them. Opinions presented in this report apply to the site conditions and features as they existed at the time of SRK's investigations, and those reasonably foreseeable. These opinions do not necessarily apply to conditions and features that may arise after the date of this Report, about which SRK had no prior knowledge nor had the opportunity to evaluate.*


# PT


O objetivo principal deste estudo será identificar as informações mínimas necessárias para realizar uma análise de estabilidade sísmica das barragens de rejeitos B1 e B2 no local de Jacobina, como parte dos estudos de segurança da barragem (DSR) que estão sendo realizados pela equipe de projeto da SRK.

Os principais objetivos deste estudo serão

- Revisar o contexto sísmico da região da Bahia e as informações de base relacionadas ao risco sísmico do site do projeto, com base nas informações disponíveis até o momento. 

- Identificar normas nacionais e internacionais, diretrizes de projeto e recomendações relacionadas ao projeto sísmico das instalações de represamento de rejeitos.

- Revisar o estado atual das metodologias de projeto sísmico e identificar lacunas de informação que possam existir no momento da avaliação final da segurança da barragem.

Traduzido com a versão gratuita do tradutor - www.DeepL.com/Translator
:::



